Fetosense integration
PSMRI/HWC-API pull request #45
Opened 2023-08-03 05:54 UTC by swetatech24

2023-08-03 08:36 UTC, Anjana2310 approved these changes
@swetatech24 Looks fine to me

2023-08-04 09:38 UTC, harimohanr commented on src/main/java/com/iemr/hwc/data/foetalmonitor/FoetalMonitor.java
> +	private Long partnerFoetalMonitorId;
@swetatech24 @Anjana2310 Please change partnerFoetalMonitorId to foetalMonitorId

2023-08-04 09:40 UTC, harimohanr commented on src/main/java/com/iemr/hwc/data/foetalmonitor/FoetalMonitor.java
> +		this.cmMotherId = foetalMonitorMotherID;
@swetatech24 @Anjana2310 Can we rename foetalMonitoryMotherID to just montherId?

2023-08-04 09:41 UTC, harimohanr commented on src/main/java/com/iemr/hwc/data/foetalmonitor/FoetalMonitor.java
> +		this.partnerId = foetalMonitorPartnerID;
@swetatech24 @Anjana2310 Can we rename foetalMonitorPartnerID to just partnerId?

2023-08-04 09:43 UTC, harimohanr commented on src/main/java/com/iemr/hwc/data/login/MasterVan.java
> +	private Boolean vanfoetalMonitorIDmapped;
@swetatech24 Shouldn't this field name be vanFoetalMonitorMapped?

2023-08-04 09:46 UTC, harimohanr requested changes
@swetatech24 @Anjana2310 Suggested few changes. Please address that and merge it.

2023-08-16 04:42 UTC, harimohanr approved these changes

2023-08-16 04:42 UTC, merged